// Package generate scans Go packages for structs marked with // generate:reset
// and emits Reset() methods into a reset.gen.go file inside each package.
package generate

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"golang.org/x/tools/go/packages"
)

// Marker is the doc-comment trigger that opts a struct into Reset generation.
const Marker = "generate:reset"

// GeneratedFile is the name of the file written into each marked package.
const GeneratedFile = "reset.gen.go"

const generatedHeader = "// Code generated by cmd/reset; DO NOT EDIT."

// Run walks rootDir recursively and (re)writes reset.gen.go for every package
// containing at least one struct marked with // generate:reset.
func Run(rootDir string) error {
	dirs, err := goDirs(rootDir)
	if err != nil {
		return err
	}
	for _, dir := range dirs {
		data, ok, err := generatePackage(dir)
		if err != nil {
			return fmt.Errorf("%s: %w", dir, err)
		}
		if !ok {
			continue
		}
		out := filepath.Join(dir, GeneratedFile)
		if err := os.WriteFile(out, data, 0644); err != nil {
			return fmt.Errorf("write %s: %w", out, err)
		}
	}
	return nil
}

func goDirs(root string) ([]string, error) {
	seen := map[string]bool{}
	var dirs []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			base := d.Name()
			if path != root && (strings.HasPrefix(base, ".") || base == "vendor" || base == "testdata" || base == "node_modules") {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(d.Name(), ".go") || strings.HasSuffix(d.Name(), "_test.go") {
			return nil
		}
		dir := filepath.Dir(path)
		if !seen[dir] {
			seen[dir] = true
			dirs = append(dirs, dir)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(dirs)
	return dirs, nil
}

// generatePackage loads the package in dir and returns generated bytes plus
// whether anything was generated. The second return value is false when the
// package contains no marked structs.
func generatePackage(dir string) ([]byte, bool, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedCompiledGoFiles,
		Dir:  dir,
	}
	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return nil, false, err
	}
	if len(pkgs) == 0 {
		return nil, false, nil
	}
	pkg := pkgs[0]
	if len(pkg.Errors) > 0 {
		return nil, false, fmt.Errorf("load %s: %v", pkg.PkgPath, pkg.Errors[0])
	}

	marked := findMarked(pkg)
	if len(marked) == 0 {
		return nil, false, nil
	}
	data, err := buildFile(pkg, marked)
	if err != nil {
		return nil, false, err
	}
	return data, true, nil
}

type markedStruct struct {
	name   string
	named  *types.Named
	fields []*types.Var
}

func findMarked(pkg *packages.Package) []markedStruct {
	names := map[string]bool{}
	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				doc := ts.Doc
				if doc == nil && len(gd.Specs) == 1 {
					doc = gd.Doc
				}
				if !hasMarker(doc) {
					continue
				}
				if _, ok := ts.Type.(*ast.StructType); !ok {
					continue
				}
				names[ts.Name.Name] = true
			}
		}
	}
	if len(names) == 0 {
		return nil
	}

	scope := pkg.Types.Scope()
	var result []markedStruct
	for name := range names {
		obj := scope.Lookup(name)
		if obj == nil {
			continue
		}
		named, ok := obj.Type().(*types.Named)
		if !ok {
			continue
		}
		st, ok := named.Underlying().(*types.Struct)
		if !ok {
			continue
		}
		ms := markedStruct{name: name, named: named}
		for i := 0; i < st.NumFields(); i++ {
			ms.fields = append(ms.fields, st.Field(i))
		}
		result = append(result, ms)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].name < result[j].name })
	return result
}

func hasMarker(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		line := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		line = strings.TrimSpace(strings.TrimPrefix(line, "/*"))
		line = strings.TrimSpace(strings.TrimSuffix(line, "*/"))
		if line == Marker {
			return true
		}
	}
	return false
}

func buildFile(pkg *packages.Package, marked []markedStruct) ([]byte, error) {
	markedSet := make(map[string]bool, len(marked))
	for _, m := range marked {
		markedSet[m.name] = true
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, generatedHeader)
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "package %s\n\n", pkg.Name)

	for _, m := range marked {
		recv := receiverName(m.name)
		fmt.Fprintf(&buf, "// Reset zeros the fields of %s; safe to call on a nil receiver.\n", m.name)
		fmt.Fprintf(&buf, "func (%s *%s) Reset() {\n", recv, m.name)
		fmt.Fprintf(&buf, "\tif %s == nil {\n\t\treturn\n\t}\n", recv)
		for _, f := range m.fields {
			for _, line := range resetField(recv, f.Name(), f.Type(), markedSet, pkg.PkgPath) {
				fmt.Fprintf(&buf, "\t%s\n", line)
			}
		}
		fmt.Fprintln(&buf, "}")
		fmt.Fprintln(&buf)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("format: %w", err)
	}
	return formatted, nil
}

func resetField(recv, name string, t types.Type, markedSet map[string]bool, pkgPath string) []string {
	expr := recv + "." + name

	if hasOrWillHaveReset(t, markedSet, pkgPath) {
		if _, isPtr := t.(*types.Pointer); isPtr {
			return []string{
				fmt.Sprintf("if %s != nil {", expr),
				fmt.Sprintf("\t%s.Reset()", expr),
				"}",
			}
		}
		return []string{fmt.Sprintf("%s.Reset()", expr)}
	}

	switch tt := t.(type) {
	case *types.Basic:
		return []string{fmt.Sprintf("%s = %s", expr, basicZero(tt))}
	case *types.Slice:
		return []string{fmt.Sprintf("%s = %s[:0]", expr, expr)}
	case *types.Map:
		return []string{fmt.Sprintf("clear(%s)", expr)}
	case *types.Pointer:
		elem := tt.Elem()
		if b, ok := elem.Underlying().(*types.Basic); ok {
			return []string{
				fmt.Sprintf("if %s != nil {", expr),
				fmt.Sprintf("\t*%s = %s", expr, basicZero(b)),
				"}",
			}
		}
		return nil
	case *types.Named:
		switch u := tt.Underlying().(type) {
		case *types.Basic:
			return []string{fmt.Sprintf("%s = %s", expr, basicZero(u))}
		case *types.Slice:
			return []string{fmt.Sprintf("%s = %s[:0]", expr, expr)}
		case *types.Map:
			return []string{fmt.Sprintf("clear(%s)", expr)}
		}
		return nil
	}
	return nil
}

func hasOrWillHaveReset(t types.Type, markedSet map[string]bool, pkgPath string) bool {
	probe := t
	if _, isPtr := t.(*types.Pointer); !isPtr {
		probe = types.NewPointer(t)
	}
	if hasResetMethod(probe) {
		return true
	}

	base := t
	if p, ok := t.(*types.Pointer); ok {
		base = p.Elem()
	}
	n, ok := base.(*types.Named)
	if !ok {
		return false
	}
	if n.Obj().Pkg() == nil || n.Obj().Pkg().Path() != pkgPath {
		return false
	}
	return markedSet[n.Obj().Name()]
}

func hasResetMethod(t types.Type) bool {
	ms := types.NewMethodSet(t)
	for i := 0; i < ms.Len(); i++ {
		m := ms.At(i).Obj()
		if m.Name() != "Reset" {
			continue
		}
		sig, ok := m.Type().(*types.Signature)
		if !ok {
			continue
		}
		if sig.Params().Len() == 0 && sig.Results().Len() == 0 {
			return true
		}
	}
	return false
}

func basicZero(b *types.Basic) string {
	switch b.Kind() {
	case types.Bool, types.UntypedBool:
		return "false"
	case types.String, types.UntypedString:
		return `""`
	}
	return "0"
}

func receiverName(typeName string) string {
	for _, r := range typeName {
		return string(unicode.ToLower(r))
	}
	return "r"
}
